### ISSUE TITLE
Subdirectory multi files aren't working

### ISSUE THREAD

**Issue by cgeney** [nhannht/obsidian-historica#14]
Hi! I love this plugin, I'm new to obsidian and this is a super convenient plugin for managing the timeline for my dnd campaign. It works great, however, I run into issues with subdirectories. I'm having an issue where, if I call files that are in a folder (subdirectory), it breaks the whole function and it won't even try to make a timeline.

```historica

include_files=["Timeline/Prologue.md", "Timeline/Crown.md"]

```
Not sure the issue here but I love your plugin so I really hope it can work

**Comment by nhannht** [comment]
It is bugged everywhere. Sorry for this messed.

**Comment by cgeney** [comment]
I figured it out -- it doesn't have anything to do with subdirectories, it just hates that I had a table in my file. The table is what broke it. Well, I can work around that, but just letting you know

**Comment by nhannht** [comment]
The way Historica interact with users is breaking change, so this issues become outdated. Thank you :cupid: :love_you_gesture:
