### ISSUE TITLE
Bug or Android issue

### ISSUE THREAD

**Issue by merlinuwe** [nhannht/obsidian-historica#2]
Thanks for your great plugin.

The plugin version is 0.15, I only get 0.1.3 on Android 11, even if I reinstall. Doesn't it support Android at the moment?

if I try to update, I get the same release again and again.

**Comment by nhannht** [comment]
Thank you for reporting the bug.

I just consulted support from the Obsidian internal team and know the root of the problem. Now you can download the latest release 0.2.2. I am sure the problem will go away. (I had been testing with a temporary vault to make sure the version of the release was updated to date)
