### ISSUE TITLE
Doesn't work at all for me

### ISSUE THREAD

**Issue by Zash1** [nhannht/obsidian-historica#4]
Hey! I didn't know where to ask, so I hope it's okay, that I reach out this way. I downloaded your plugin today to use it for my studies, but I can't get it to work. I tried all the commands in the documentation and wrote some myself with my own prompts but nothing seems to do what it's supposed to do. The Plugin is installed and enabled. Does it maybe have an issue with other languages? 
This is what I did: 

- In Nachkriegszeit und 1950 wesentliche Beiträge zur Entstehung der Teildisziplin. 
- Begriff Organisationspsychologie erst 1960 etabliert.
```historica
style=2
[query.from-1950-to-1960]
start="1950"
end="1960"
```
![image](https://github.com/nhannht/obsidian-historica/assets/58184421/eda324c6-4f16-433f-ae77-af9a34a7d2e2)

Thank you in advance for your help.

**Comment by nhannht** [comment]
- Sorry for the inconvenience, I will improve it later.
-  This plugin by default works with only English. I will add functionality for switching between languages. However, I am unsure if this plugin in Deutsch can achieve the same usefulness. anyway I will try, thank you for the report

**Comment by Azmoinal** [comment]
I know that probably is out of the scope for your plugin but for other languages, do you consider the possibilities to use inline tags? 

I’m thinking about a list of tags that your plugin could identifies reporting to the “standard” English. 

I’m not a English native speaker so if you want to use your plugin (that seems very nice) I should put an English sentence in my note just to enable it.

**Comment by nhannht** [comment]
> I know that probably is out of the scope for your plugin but for other languages, do you consider the possibilities to use inline tags?
> 
> I’m thinking about a list of tags that your plugin could identifies reporting to the “standard” English.
> 
> I’m not an English native speaker so if you want to use your plugin (that seems very nice) I should put an English sentence in my note just to enable it.


Thank you for giving me suggestions. Can you explain a bit clearer about what you want? Maybe give me examples. I still not understand what you mean about `inline tag`.

**Comment by Azmoinal** [comment]
I was thinking about adding a #tag into the document to add a time context putting the same info but in a different way that clarifies it is not text. For instance #now, #twohoursago or a specific date #2023-02-31.

I don't know if it could be feasible.

As an example I could write a block of text and after putting a tag to clarifies when it happened. 

`La bomba non attesa di toccare terra per esplodere. #1945-08-06`

**Comment by nhannht** [comment]
@Azmoinal thank you, I will try to implement your idea. 

This plugin will try to split the markdown content to `sentences` before doing extracting time. That is why in the example `Martin era morto ma non era la brutta notizia. #1960-08-06_21:23`. Which using 2 sentences, split by a dot, is not fit for the system now. 

About your idea, I understand that you want to make the smallest atoms be a group of sentences (paragraphs) instead of just one sentence. And give the user a choice to explicitly choose the time to plot if there is none/multi-time in that group of sentences. 


 Maybe I will try to add some function that uses hidden HTML tags to define a group of sentences that account as paragraphs. For example:
````

<historica-block style={hidden:true} id=${block-id}>
${multi sentences go here}
</historica-block>


```historica
block_id=${block-id}
time_to_render=${time_here}
````
The idea of that plugin from the start is to make things simple and effortless as much as possible. Because there are some timeline plugins that use complicated ways to plot timelines before.

**Comment by nhannht** [comment]
So many change in new versions that this issues become outdate. And I didn't receive any answer from this kute boy
